// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseMap.proto

package NoiseMap;

public final class NoiseMap {
  private NoiseMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SamplesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NoiseMap.Samples)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    java.util.List<NoiseMap.NoiseMap.Samples.Sample> 
        getSamplesList();
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    NoiseMap.NoiseMap.Samples.Sample getSamples(int index);
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    int getSamplesCount();
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    java.util.List<? extends NoiseMap.NoiseMap.Samples.SampleOrBuilder> 
        getSamplesOrBuilderList();
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    NoiseMap.NoiseMap.Samples.SampleOrBuilder getSamplesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Message 
   * </pre>
   *
   * Protobuf type {@code NoiseMap.Samples}
   */
  public  static final class Samples extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NoiseMap.Samples)
      SamplesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Samples.newBuilder() to construct.
    private Samples(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Samples() {
      samples_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Samples(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                samples_ = new java.util.ArrayList<NoiseMap.NoiseMap.Samples.Sample>();
                mutable_bitField0_ |= 0x00000001;
              }
              samples_.add(
                  input.readMessage(NoiseMap.NoiseMap.Samples.Sample.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          samples_ = java.util.Collections.unmodifiableList(samples_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NoiseMap.NoiseMap.Samples.class, NoiseMap.NoiseMap.Samples.Builder.class);
    }

    public interface SampleOrBuilder extends
        // @@protoc_insertion_point(interface_extends:NoiseMap.Samples.Sample)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      com.google.protobuf.Timestamp getTimestamp();
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

      /**
       * <code>float longitude = 2;</code>
       */
      float getLongitude();

      /**
       * <code>float latitude = 3;</code>
       */
      float getLatitude();

      /**
       * <code>float noiseValue = 4;</code>
       */
      float getNoiseValue();
    }
    /**
     * Protobuf type {@code NoiseMap.Samples.Sample}
     */
    public  static final class Sample extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:NoiseMap.Samples.Sample)
        SampleOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Sample.newBuilder() to construct.
      private Sample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Sample() {
        longitude_ = 0F;
        latitude_ = 0F;
        noiseValue_ = 0F;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Sample(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.Timestamp.Builder subBuilder = null;
                if (timestamp_ != null) {
                  subBuilder = timestamp_.toBuilder();
                }
                timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(timestamp_);
                  timestamp_ = subBuilder.buildPartial();
                }

                break;
              }
              case 21: {

                longitude_ = input.readFloat();
                break;
              }
              case 29: {

                latitude_ = input.readFloat();
                break;
              }
              case 37: {

                noiseValue_ = input.readFloat();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_Sample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_Sample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NoiseMap.NoiseMap.Samples.Sample.class, NoiseMap.NoiseMap.Samples.Sample.Builder.class);
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private com.google.protobuf.Timestamp timestamp_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        return getTimestamp();
      }

      public static final int LONGITUDE_FIELD_NUMBER = 2;
      private float longitude_;
      /**
       * <code>float longitude = 2;</code>
       */
      public float getLongitude() {
        return longitude_;
      }

      public static final int LATITUDE_FIELD_NUMBER = 3;
      private float latitude_;
      /**
       * <code>float latitude = 3;</code>
       */
      public float getLatitude() {
        return latitude_;
      }

      public static final int NOISEVALUE_FIELD_NUMBER = 4;
      private float noiseValue_;
      /**
       * <code>float noiseValue = 4;</code>
       */
      public float getNoiseValue() {
        return noiseValue_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (timestamp_ != null) {
          output.writeMessage(1, getTimestamp());
        }
        if (longitude_ != 0F) {
          output.writeFloat(2, longitude_);
        }
        if (latitude_ != 0F) {
          output.writeFloat(3, latitude_);
        }
        if (noiseValue_ != 0F) {
          output.writeFloat(4, noiseValue_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (timestamp_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getTimestamp());
        }
        if (longitude_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, longitude_);
        }
        if (latitude_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, latitude_);
        }
        if (noiseValue_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, noiseValue_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof NoiseMap.NoiseMap.Samples.Sample)) {
          return super.equals(obj);
        }
        NoiseMap.NoiseMap.Samples.Sample other = (NoiseMap.NoiseMap.Samples.Sample) obj;

        boolean result = true;
        result = result && (hasTimestamp() == other.hasTimestamp());
        if (hasTimestamp()) {
          result = result && getTimestamp()
              .equals(other.getTimestamp());
        }
        result = result && (
            java.lang.Float.floatToIntBits(getLongitude())
            == java.lang.Float.floatToIntBits(
                other.getLongitude()));
        result = result && (
            java.lang.Float.floatToIntBits(getLatitude())
            == java.lang.Float.floatToIntBits(
                other.getLatitude()));
        result = result && (
            java.lang.Float.floatToIntBits(getNoiseValue())
            == java.lang.Float.floatToIntBits(
                other.getNoiseValue()));
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTimestamp()) {
          hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
          hash = (53 * hash) + getTimestamp().hashCode();
        }
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLongitude());
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLatitude());
        hash = (37 * hash) + NOISEVALUE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getNoiseValue());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static NoiseMap.NoiseMap.Samples.Sample parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(NoiseMap.NoiseMap.Samples.Sample prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code NoiseMap.Samples.Sample}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:NoiseMap.Samples.Sample)
          NoiseMap.NoiseMap.Samples.SampleOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_Sample_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_Sample_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  NoiseMap.NoiseMap.Samples.Sample.class, NoiseMap.NoiseMap.Samples.Sample.Builder.class);
        }

        // Construct using NoiseMap.NoiseMap.Samples.Sample.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (timestampBuilder_ == null) {
            timestamp_ = null;
          } else {
            timestamp_ = null;
            timestampBuilder_ = null;
          }
          longitude_ = 0F;

          latitude_ = 0F;

          noiseValue_ = 0F;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_Sample_descriptor;
        }

        @java.lang.Override
        public NoiseMap.NoiseMap.Samples.Sample getDefaultInstanceForType() {
          return NoiseMap.NoiseMap.Samples.Sample.getDefaultInstance();
        }

        @java.lang.Override
        public NoiseMap.NoiseMap.Samples.Sample build() {
          NoiseMap.NoiseMap.Samples.Sample result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public NoiseMap.NoiseMap.Samples.Sample buildPartial() {
          NoiseMap.NoiseMap.Samples.Sample result = new NoiseMap.NoiseMap.Samples.Sample(this);
          if (timestampBuilder_ == null) {
            result.timestamp_ = timestamp_;
          } else {
            result.timestamp_ = timestampBuilder_.build();
          }
          result.longitude_ = longitude_;
          result.latitude_ = latitude_;
          result.noiseValue_ = noiseValue_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof NoiseMap.NoiseMap.Samples.Sample) {
            return mergeFrom((NoiseMap.NoiseMap.Samples.Sample)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(NoiseMap.NoiseMap.Samples.Sample other) {
          if (other == NoiseMap.NoiseMap.Samples.Sample.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            mergeTimestamp(other.getTimestamp());
          }
          if (other.getLongitude() != 0F) {
            setLongitude(other.getLongitude());
          }
          if (other.getLatitude() != 0F) {
            setLatitude(other.getLatitude());
          }
          if (other.getNoiseValue() != 0F) {
            setNoiseValue(other.getNoiseValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          NoiseMap.NoiseMap.Samples.Sample parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (NoiseMap.NoiseMap.Samples.Sample) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.Timestamp timestamp_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return timestampBuilder_ != null || timestamp_ != null;
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public com.google.protobuf.Timestamp getTimestamp() {
          if (timestampBuilder_ == null) {
            return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
          } else {
            return timestampBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder setTimestamp(com.google.protobuf.Timestamp value) {
          if (timestampBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            timestamp_ = value;
            onChanged();
          } else {
            timestampBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder setTimestamp(
            com.google.protobuf.Timestamp.Builder builderForValue) {
          if (timestampBuilder_ == null) {
            timestamp_ = builderForValue.build();
            onChanged();
          } else {
            timestampBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
          if (timestampBuilder_ == null) {
            if (timestamp_ != null) {
              timestamp_ =
                com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
            } else {
              timestamp_ = value;
            }
            onChanged();
          } else {
            timestampBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          if (timestampBuilder_ == null) {
            timestamp_ = null;
            onChanged();
          } else {
            timestamp_ = null;
            timestampBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
          
          onChanged();
          return getTimestampFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
          if (timestampBuilder_ != null) {
            return timestampBuilder_.getMessageOrBuilder();
          } else {
            return timestamp_ == null ?
                com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
          }
        }
        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
            getTimestampFieldBuilder() {
          if (timestampBuilder_ == null) {
            timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                    getTimestamp(),
                    getParentForChildren(),
                    isClean());
            timestamp_ = null;
          }
          return timestampBuilder_;
        }

        private float longitude_ ;
        /**
         * <code>float longitude = 2;</code>
         */
        public float getLongitude() {
          return longitude_;
        }
        /**
         * <code>float longitude = 2;</code>
         */
        public Builder setLongitude(float value) {
          
          longitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float longitude = 2;</code>
         */
        public Builder clearLongitude() {
          
          longitude_ = 0F;
          onChanged();
          return this;
        }

        private float latitude_ ;
        /**
         * <code>float latitude = 3;</code>
         */
        public float getLatitude() {
          return latitude_;
        }
        /**
         * <code>float latitude = 3;</code>
         */
        public Builder setLatitude(float value) {
          
          latitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float latitude = 3;</code>
         */
        public Builder clearLatitude() {
          
          latitude_ = 0F;
          onChanged();
          return this;
        }

        private float noiseValue_ ;
        /**
         * <code>float noiseValue = 4;</code>
         */
        public float getNoiseValue() {
          return noiseValue_;
        }
        /**
         * <code>float noiseValue = 4;</code>
         */
        public Builder setNoiseValue(float value) {
          
          noiseValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float noiseValue = 4;</code>
         */
        public Builder clearNoiseValue() {
          
          noiseValue_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:NoiseMap.Samples.Sample)
      }

      // @@protoc_insertion_point(class_scope:NoiseMap.Samples.Sample)
      private static final NoiseMap.NoiseMap.Samples.Sample DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new NoiseMap.NoiseMap.Samples.Sample();
      }

      public static NoiseMap.NoiseMap.Samples.Sample getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Sample>
          PARSER = new com.google.protobuf.AbstractParser<Sample>() {
        @java.lang.Override
        public Sample parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sample(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Sample> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Sample> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public NoiseMap.NoiseMap.Samples.Sample getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SAMPLES_FIELD_NUMBER = 1;
    private java.util.List<NoiseMap.NoiseMap.Samples.Sample> samples_;
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    public java.util.List<NoiseMap.NoiseMap.Samples.Sample> getSamplesList() {
      return samples_;
    }
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    public java.util.List<? extends NoiseMap.NoiseMap.Samples.SampleOrBuilder> 
        getSamplesOrBuilderList() {
      return samples_;
    }
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    public int getSamplesCount() {
      return samples_.size();
    }
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    public NoiseMap.NoiseMap.Samples.Sample getSamples(int index) {
      return samples_.get(index);
    }
    /**
     * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
     */
    public NoiseMap.NoiseMap.Samples.SampleOrBuilder getSamplesOrBuilder(
        int index) {
      return samples_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < samples_.size(); i++) {
        output.writeMessage(1, samples_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < samples_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, samples_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NoiseMap.NoiseMap.Samples)) {
        return super.equals(obj);
      }
      NoiseMap.NoiseMap.Samples other = (NoiseMap.NoiseMap.Samples) obj;

      boolean result = true;
      result = result && getSamplesList()
          .equals(other.getSamplesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSamplesCount() > 0) {
        hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getSamplesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NoiseMap.NoiseMap.Samples parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NoiseMap.NoiseMap.Samples parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NoiseMap.NoiseMap.Samples parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NoiseMap.NoiseMap.Samples parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NoiseMap.NoiseMap.Samples prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message 
     * </pre>
     *
     * Protobuf type {@code NoiseMap.Samples}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NoiseMap.Samples)
        NoiseMap.NoiseMap.SamplesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NoiseMap.NoiseMap.Samples.class, NoiseMap.NoiseMap.Samples.Builder.class);
      }

      // Construct using NoiseMap.NoiseMap.Samples.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSamplesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (samplesBuilder_ == null) {
          samples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          samplesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NoiseMap.NoiseMap.internal_static_NoiseMap_Samples_descriptor;
      }

      @java.lang.Override
      public NoiseMap.NoiseMap.Samples getDefaultInstanceForType() {
        return NoiseMap.NoiseMap.Samples.getDefaultInstance();
      }

      @java.lang.Override
      public NoiseMap.NoiseMap.Samples build() {
        NoiseMap.NoiseMap.Samples result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NoiseMap.NoiseMap.Samples buildPartial() {
        NoiseMap.NoiseMap.Samples result = new NoiseMap.NoiseMap.Samples(this);
        int from_bitField0_ = bitField0_;
        if (samplesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            samples_ = java.util.Collections.unmodifiableList(samples_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.samples_ = samples_;
        } else {
          result.samples_ = samplesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NoiseMap.NoiseMap.Samples) {
          return mergeFrom((NoiseMap.NoiseMap.Samples)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NoiseMap.NoiseMap.Samples other) {
        if (other == NoiseMap.NoiseMap.Samples.getDefaultInstance()) return this;
        if (samplesBuilder_ == null) {
          if (!other.samples_.isEmpty()) {
            if (samples_.isEmpty()) {
              samples_ = other.samples_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSamplesIsMutable();
              samples_.addAll(other.samples_);
            }
            onChanged();
          }
        } else {
          if (!other.samples_.isEmpty()) {
            if (samplesBuilder_.isEmpty()) {
              samplesBuilder_.dispose();
              samplesBuilder_ = null;
              samples_ = other.samples_;
              bitField0_ = (bitField0_ & ~0x00000001);
              samplesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSamplesFieldBuilder() : null;
            } else {
              samplesBuilder_.addAllMessages(other.samples_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NoiseMap.NoiseMap.Samples parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NoiseMap.NoiseMap.Samples) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<NoiseMap.NoiseMap.Samples.Sample> samples_ =
        java.util.Collections.emptyList();
      private void ensureSamplesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          samples_ = new java.util.ArrayList<NoiseMap.NoiseMap.Samples.Sample>(samples_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          NoiseMap.NoiseMap.Samples.Sample, NoiseMap.NoiseMap.Samples.Sample.Builder, NoiseMap.NoiseMap.Samples.SampleOrBuilder> samplesBuilder_;

      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public java.util.List<NoiseMap.NoiseMap.Samples.Sample> getSamplesList() {
        if (samplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(samples_);
        } else {
          return samplesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public int getSamplesCount() {
        if (samplesBuilder_ == null) {
          return samples_.size();
        } else {
          return samplesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public NoiseMap.NoiseMap.Samples.Sample getSamples(int index) {
        if (samplesBuilder_ == null) {
          return samples_.get(index);
        } else {
          return samplesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder setSamples(
          int index, NoiseMap.NoiseMap.Samples.Sample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.set(index, value);
          onChanged();
        } else {
          samplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder setSamples(
          int index, NoiseMap.NoiseMap.Samples.Sample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.set(index, builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder addSamples(NoiseMap.NoiseMap.Samples.Sample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.add(value);
          onChanged();
        } else {
          samplesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder addSamples(
          int index, NoiseMap.NoiseMap.Samples.Sample value) {
        if (samplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSamplesIsMutable();
          samples_.add(index, value);
          onChanged();
        } else {
          samplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder addSamples(
          NoiseMap.NoiseMap.Samples.Sample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.add(builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder addSamples(
          int index, NoiseMap.NoiseMap.Samples.Sample.Builder builderForValue) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.add(index, builderForValue.build());
          onChanged();
        } else {
          samplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder addAllSamples(
          java.lang.Iterable<? extends NoiseMap.NoiseMap.Samples.Sample> values) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, samples_);
          onChanged();
        } else {
          samplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder clearSamples() {
        if (samplesBuilder_ == null) {
          samples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          samplesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public Builder removeSamples(int index) {
        if (samplesBuilder_ == null) {
          ensureSamplesIsMutable();
          samples_.remove(index);
          onChanged();
        } else {
          samplesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public NoiseMap.NoiseMap.Samples.Sample.Builder getSamplesBuilder(
          int index) {
        return getSamplesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public NoiseMap.NoiseMap.Samples.SampleOrBuilder getSamplesOrBuilder(
          int index) {
        if (samplesBuilder_ == null) {
          return samples_.get(index);  } else {
          return samplesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public java.util.List<? extends NoiseMap.NoiseMap.Samples.SampleOrBuilder> 
           getSamplesOrBuilderList() {
        if (samplesBuilder_ != null) {
          return samplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(samples_);
        }
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public NoiseMap.NoiseMap.Samples.Sample.Builder addSamplesBuilder() {
        return getSamplesFieldBuilder().addBuilder(
            NoiseMap.NoiseMap.Samples.Sample.getDefaultInstance());
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public NoiseMap.NoiseMap.Samples.Sample.Builder addSamplesBuilder(
          int index) {
        return getSamplesFieldBuilder().addBuilder(
            index, NoiseMap.NoiseMap.Samples.Sample.getDefaultInstance());
      }
      /**
       * <code>repeated .NoiseMap.Samples.Sample samples = 1;</code>
       */
      public java.util.List<NoiseMap.NoiseMap.Samples.Sample.Builder> 
           getSamplesBuilderList() {
        return getSamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          NoiseMap.NoiseMap.Samples.Sample, NoiseMap.NoiseMap.Samples.Sample.Builder, NoiseMap.NoiseMap.Samples.SampleOrBuilder> 
          getSamplesFieldBuilder() {
        if (samplesBuilder_ == null) {
          samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              NoiseMap.NoiseMap.Samples.Sample, NoiseMap.NoiseMap.Samples.Sample.Builder, NoiseMap.NoiseMap.Samples.SampleOrBuilder>(
                  samples_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          samples_ = null;
        }
        return samplesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NoiseMap.Samples)
    }

    // @@protoc_insertion_point(class_scope:NoiseMap.Samples)
    private static final NoiseMap.NoiseMap.Samples DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NoiseMap.NoiseMap.Samples();
    }

    public static NoiseMap.NoiseMap.Samples getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Samples>
        PARSER = new com.google.protobuf.AbstractParser<Samples>() {
      @java.lang.Override
      public Samples parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Samples(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Samples> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Samples> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NoiseMap.NoiseMap.Samples getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoiseMap_Samples_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NoiseMap_Samples_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoiseMap_Samples_Sample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NoiseMap_Samples_Sample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016NoiseMap.proto\022\010NoiseMap\032\037google/proto" +
      "buf/timestamp.proto\"\246\001\n\007Samples\022)\n\007sampl" +
      "es\030\001 \003(\0132\030.NoiseMap.Samples.Sample\032p\n\006Sa" +
      "mple\022-\n\ttimestamp\030\001 \001(\0132\032.google.protobu" +
      "f.Timestamp\022\021\n\tlongitude\030\002 \001(\002\022\020\n\010latitu" +
      "de\030\003 \001(\002\022\022\n\nnoiseValue\030\004 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_NoiseMap_Samples_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NoiseMap_Samples_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NoiseMap_Samples_descriptor,
        new java.lang.String[] { "Samples", });
    internal_static_NoiseMap_Samples_Sample_descriptor =
      internal_static_NoiseMap_Samples_descriptor.getNestedTypes().get(0);
    internal_static_NoiseMap_Samples_Sample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NoiseMap_Samples_Sample_descriptor,
        new java.lang.String[] { "Timestamp", "Longitude", "Latitude", "NoiseValue", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
